<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => 'א נייַ אַפּ צו מאַכן סקעדזשולינג ווי פּשוט ווי עס זאָל זיין .',
    'Building Places' => 'בילדינג פּלאַסעס',
    'Coming Soon' => 'קומענדיק באַלד',
    'Episode 1' => 'עפּיסאָדע 1',
    'Episode 2' => 'עפּיסאָדע 2',
    'Episode 3' => 'עפּיסאָדע 3',
    'Feature Requirements' => 'שטריך רעקווירעמענץ',
    'Follow' => 'נאָכפאָלגן',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => 'גיי צוזאמען מיט אונדזער טוטאָריאַל סעריע אין טוץ + ווי מיר בויען פאַרזאַמלונג פּלאַננער שריט דורך שריט . אין דעם עפּיזאָד מיר רעדן וועגן סטאַרטאַפּס אין אַלגעמיין און די צילן פֿאַר אונדזער אַפּלאַקיישאַן .',
    'Getting Started' => 'געטינג סטאַרטעד',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'אין עפּיסאָדע 2 , מיר פאַרנעם אויס די פֿעיִקייטן אַז מיר וועט דאַרפֿן פֿאַר אַ מינימום ווייאַבאַל פּראָדוקט און די דייטאַבייס סטשעמאַ אַז וועט שטיצן עס .',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => 'אין עפּיסאָדע 3 , מיר בויען קאָד צו געבן באַגעגעניש ערטער , ינטאַגרייטינג מיט HTML 5 געאָלאָקאַטיאָן , Google מאַפּס און Google פּלאַסעס .',
    'Learn More' => 'לערן מער',
    'About' => 'וועגן',
    'Add Current Location' => 'לייג קראַנט אָרט',
    'Add a Google {modelClass}' => 'לייג אַ גוגל {modelClass}',
    'Are you sure you want to delete this item?' => 'ביסט איר זיכער איר ווילן צו אויסמעקן דעם פּאָזיציע ?',
    'Contact' => 'קאָנטאַקט',
    'Create' => 'מאַכן',
    'Create {modelClass}' => 'מאַכן {modelClass}',
    'Created At' => 'באשאפן אין',
    'Created By' => 'באשאפן דורך',
    'Delete' => 'ויסמעקן',
    'Full Address' => 'גאַנץ אַדרעס',
    'Google Place ID' => 'Google אָרט שייַן',
    'Home' => 'היים',
    'ID' => 'שייַן',
    'Login' => 'לאָגין',
    'Logout' => 'לאָגאָוט',
    'Meeting Type' => 'פאַרזאַמלונג טיפּ',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => 'מיטינגז',
    'Message' => 'אָנזאָג',
    'Name' => 'נאָמען',
    'Notes' => 'נאָטעס',
    'Owner ID' => 'באַזיצער שייַן',
    'Place Type' => 'אָרט טיפּ',
    'Places' => 'ערטער',
    'Reset' => 'באַשטעטיק',
    'Search' => 'זוכן',
    'Signup' => 'סיגנופּ',
    'Slug' => 'מעטאַלכל',
    'Status' => 'מאַצעוו',
    'Update' => 'דערהייַנטיקן',
    'Update {modelClass}: ' => 'דערהייַנטיקן {modelClass} :',
    'Updated At' => 'דערהייַנטיקט אין',
    'Vicinity' => 'געגנט',
    'Website' => 'וועבזייַטל',
];