<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => '新しいアプリは、それがあるべきようにスケジューリングは同じくらい簡単にします。',
    'Building Places' => 'ビル場所',
    'Coming Soon' => '近日公開',
    'Episode 1' => 'エピソード1',
    'Episode 2' => 'エピソード2',
    'Episode 3' => 'エピソード3',
    'Feature Requirements' => '機能要件',
    'Follow' => '続く',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => '我々はステップによってプランナーステップ会議構築する+ Tutsで私達のチュートリアルシリーズと一緒に従う。このエピソードでは、一般的にはスタートアップや我々のアプリケーションの目標について話しています。',
    'Getting Started' => '入門',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'エピソード2では、我々は最小実行可能な製品とそれをサポートするデータベース·スキーマのために必要があるでしょう特徴から我々スコープ。',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => '第3話では、 HTML 5のジオロケーション、 GoogleマップとGoogleプレイスとの統合、場所を満たす有効にするためにコードをビルド。',
    'Learn More' => 'もっと詳しく知る',
    'About' => '約',
    'Add Current Location' => '現在の位置に追加',
    'Add a Google {modelClass}' => 'Googleに追加 {modelClass}',
    'Are you sure you want to delete this item?' => 'あなたはこの項目を削除してもよろしいていますか？',
    'Contact' => 'コンタクト',
    'Create' => '作る',
    'Create {modelClass}' => '作る {modelClass}',
    'Created At' => 'で作成された',
    'Created By' => 'によって作成された',
    'Delete' => '削除',
    'Full Address' => '完全な住所',
    'Google Place ID' => 'グーグル·プレイスID',
    'Home' => 'ホーム',
    'ID' => 'ID',
    'Login' => 'ログイン',
    'Logout' => 'ログアウト',
    'Meeting Type' => '会議の種類',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => '会議',
    'Message' => 'メッセージ',
    'Name' => '名前',
    'Notes' => '注釈',
    'Owner ID' => '所有者ID',
    'Place Type' => '置きタイプ',
    'Places' => '場所',
    'Reset' => 'リセット',
    'Search' => '検索',
    'Signup' => 'サインアップ',
    'Slug' => 'ナメクジ',
    'Status' => 'ステータス',
    'Update' => 'アップデート',
    'Update {modelClass}: ' => 'アップデート {modelClass} ：',
    'Updated At' => 'で更新',
    'Vicinity' => '近く',
    'Website' => 'ウェブサイト',
];