<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => '一个新的应用程序，使调度简单，因为它应该是。',
    'Building Places' => '建设地点',
    'Coming Soon' => '即将推出',
    'Episode 1' => '第1集',
    'Episode 2' => '第2集',
    'Episode 3' => '第3集',
    'Feature Requirements' => '功能要求',
    'Follow' => '跟随',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => '随着我们的教程系列的TUTS遵循+为我们建立一个脚印会议策划的一步。在这一集里，我们谈论的一般创业公司和我们的应用程序的目标。',
    'Getting Started' => '入门',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => '在第2集，我们的范围了，我们就需要一个最低可行的产品，这将支持它的数据库模式的功能。',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => '在第3集，我们建立的代码，使会议场所，与HTML 5地理位置，谷歌地图和谷歌的地方整合。',
    'Learn More' => '了解更多',
    'About' => '大约',
    'Add Current Location' => '添加当前位置',
    'Add a Google {modelClass}' => '添加谷歌 {modelClass}',
    'Are you sure you want to delete this item?' => '你确定你要删除这个项目吗？',
    'Contact' => '联系',
    'Create' => '创建',
    'Create {modelClass}' => '创建 {modelClass}',
    'Created At' => '在创建',
    'Created By' => '创建人',
    'Delete' => '删除',
    'Full Address' => '详细地址',
    'Google Place ID' => '谷歌将ID',
    'Home' => '家',
    'ID' => 'ID',
    'Login' => '登录',
    'Logout' => '注销',
    'Meeting Type' => '会议类型',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => '会议',
    'Message' => '信息',
    'Name' => '名字',
    'Notes' => '笔记',
    'Owner ID' => '店主ID',
    'Place Type' => '地方类型',
    'Places' => '地方',
    'Reset' => '重置',
    'Search' => '搜索',
    'Signup' => '报名',
    'Slug' => '金属块',
    'Status' => '状态',
    'Update' => '更新',
    'Update {modelClass}: ' => '更新 {modelClass} ：',
    'Updated At' => '在更新',
    'Vicinity' => '附近',
    'Website' => '网站',
];