<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => 'Una nuova app per fare la pianificazione semplice come dovrebbe essere .',
    'Building Places' => 'Costruire Places',
    'Coming Soon' => 'Prossimamente',
    'Episode 1' => 'Episode 1',
    'Episode 2' => 'Episode 2',
    'Episode 3' => 'Episode 3',
    'Feature Requirements' => 'Requisiti Feature',
    'Follow' => 'seguire',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => 'Seguire con la nostra serie di tutorial in Tuts + come costruiamo Meeting Planner passo dopo passo . In questo episodio si parla di start-up in generale e gli obiettivi per la nostra applicazione .',
    'Getting Started' => 'iniziare',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'Nell\'episodio 2 , abbiamo portata fuori le caratteristiche che ci servono per un prodotto valido minimo e lo schema del database che lo sosterrà .',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => 'In Episode 3 , costruiamo codice per attivare luoghi di incontro , integrazione con HTML 5 Geolocation , Google Maps e Google Places .',
    'Learn More' => 'saperne Di Più',
    'About' => 'su',
    'Add Current Location' => 'Aggiungi posizione corrente',
    'Add a Google {modelClass}' => 'Aggiungi un Google {modelClass}',
    'Are you sure you want to delete this item?' => 'Sei sicuro di voler eliminare questo articolo?',
    'Contact' => 'contatto',
    'Create' => 'creare',
    'Create {modelClass}' => 'creare {modelClass}',
    'Created At' => 'creato il',
    'Created By' => 'creato da',
    'Delete' => 'cancellare',
    'Full Address' => 'Indirizzo completo',
    'Google Place ID' => 'Google Luogo ID',
    'Home' => 'casa',
    'ID' => 'ID',
    'Login' => 'login',
    'Logout' => 'Logout',
    'Meeting Type' => 'tipo di riunione',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => 'Riunioni',
    'Message' => 'messaggio',
    'Name' => 'nome',
    'Notes' => 'Note',
    'Owner ID' => 'proprietario ID',
    'Place Type' => 'luogo Type',
    'Places' => 'Places',
    'Reset' => 'reset',
    'Search' => 'ricerca',
    'Signup' => 'Iscriviti',
    'Slug' => 'lumaca',
    'Status' => 'stato',
    'Update' => 'aggiornare',
    'Update {modelClass}: ' => 'aggiornare {modelClass} :',
    'Updated At' => 'aggiornato A',
    'Vicinity' => 'vicinanza',
    'Website' => 'sito web',
];