<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => 'Eine neue App , um die Planung so einfach, wie es sein sollte.',
    'Building Places' => 'Gebäude Places',
    'Coming Soon' => 'kommt Bald',
    'Episode 1' => 'Episode 1',
    'Episode 2' => 'Episode 2',
    'Episode 3' => 'Episode 3',
    'Feature Requirements' => 'Featureanforderungen',
    'Follow' => 'folgen',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => 'Folgen Sie zusammen mit unseren Tutorials an Tuts + , wie wir bauen Meeting Planner Schritt für Schritt. In dieser Folge uns über Start-ups im Allgemeinen und die Ziele für unsere Anwendung zu sprechen.',
    'Getting Started' => 'Einstieg',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'In Episode 2 , wir Umfang aus der Features, die wir für mindestens marktfähiges Produkt und das Datenbankschema , die es unterstützen müssen .',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => 'In Episode 3 bauen wir Code Treffpunkte , die Integration mit HTML 5 Geolocation , Google Maps und Google Places zu ermöglichen.',
    'Learn More' => 'Erfahren Sie Mehr',
    'About' => 'über',
    'Add Current Location' => 'Fügen Aufenthaltsort',
    'Add a Google {modelClass}' => 'Fügen Sie ein Google {modelClass}',
    'Are you sure you want to delete this item?' => 'Sind Sie sicher, Sie wollen diesen Inhalt löschen ?',
    'Contact' => 'Kontakt',
    'Create' => 'schaffen',
    'Create {modelClass}' => 'schaffen {modelClass}',
    'Created At' => 'Erstellt am',
    'Created By' => 'Erstellt von',
    'Delete' => 'löschen',
    'Full Address' => 'Vollständige Adresse',
    'Google Place ID' => 'Google Platz ID',
    'Home' => 'Zuhause',
    'ID' => 'Identifikation',
    'Login' => 'Einloggen',
    'Logout' => 'Logout',
    'Meeting Type' => 'Treffen Typ',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => 'Meetings',
    'Message' => 'Nachricht',
    'Name' => 'Name',
    'Notes' => 'Aufzeichnungen',
    'Owner ID' => 'Besitzer-ID',
    'Place Type' => 'Platz Typ',
    'Places' => 'Places',
    'Reset' => 'rücksetzen',
    'Search' => 'Suche',
    'Signup' => 'Anmeldung',
    'Slug' => 'Schnecke',
    'Status' => 'Status',
    'Update' => 'Aktualisierung',
    'Update {modelClass}: ' => 'Aktualisierung {modelClass} :',
    'Updated At' => 'aktualisiert An',
    'Vicinity' => 'Umgebung',
    'Website' => 'Webseite',
];