<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => 'אפליקציה חדשה כדי להפוך את התזמון פשוט כמו שזה צריך להיות .',
    'Building Places' => 'מקומות בניין',
    'Coming Soon' => 'בקרוב',
    'Episode 1' => 'פרק 1',
    'Episode 2' => 'פרק 2',
    'Episode 3' => 'פרק 3',
    'Feature Requirements' => 'דרישות תכונה',
    'Follow' => 'עקוב',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => 'פעל יחד הסדרה של מורנובTuts עם + כמו שאנחנו בונים דיונים צעד מתכנן אחר צעד. בפרק זה אנו מדברים על חברות סטארט-אפ באופן כלליוהמטרותליישום שלנו .',
    'Getting Started' => 'תחילת עבודה',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'בפרק 2 , אנחנו היקף את התכונותשאנו זקוקים לו למוצר בר קיימא מינימוםוסכימת מסד נתוניםשיתמכו בו .',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => 'בפרק 3 , אנו בונים קוד כדי לאפשר מקומות מפגש , שילוב עם Geolocation HTML 5 , Google Maps ו- Google מקומות .',
    'Learn More' => 'מידע נוסף',
    'About' => 'אודות',
    'Add Current Location' => 'הוספת מיקום נוכחי',
    'Add a Google {modelClass}' => 'הוסף Google {modelClass}',
    'Are you sure you want to delete this item?' => 'האם אתה בטוח שאתה רוצה למחוק פריט זה?',
    'Contact' => 'צור קשר עם',
    'Create' => 'צור',
    'Create {modelClass}' => 'צור {modelClass}',
    'Created At' => 'נוצר ב',
    'Created By' => 'נוצר על-ידי',
    'Delete' => 'מחק',
    'Full Address' => 'כתובת מלאה',
    'Google Place ID' => 'מקום ID Google',
    'Home' => 'בית',
    'ID' => 'זיהוי',
    'Login' => 'כניסה',
    'Logout' => 'התנתקות',
    'Meeting Type' => 'סוג דיונים',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => 'מפגשים',
    'Message' => 'הודעה',
    'Name' => 'שם',
    'Notes' => 'הערות',
    'Owner ID' => 'בעלי תעודת זהות',
    'Place Type' => 'סוג המקום',
    'Places' => 'מקומות',
    'Reset' => 'איפוס',
    'Search' => 'חיפוש',
    'Signup' => 'הרשמה',
    'Slug' => 'אֲסִימוֹן',
    'Status' => 'סטטוס',
    'Update' => 'עדכון',
    'Update {modelClass}: ' => 'עדכון {modelClass} :',
    'Updated At' => 'עדכון ב',
    'Vicinity' => 'קרבה',
    'Website' => 'אתר',
];