<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => 'والتطبيق الجديد لجعل جدولة بسيطة كما ينبغي أن يكون.',
    'Building Places' => 'بناء الأماكن',
    'Coming Soon' => 'قريبا',
    'Episode 1' => 'الحلقة 1',
    'Episode 2' => 'الحلقة 2',
    'Episode 3' => 'الحلقة 3',
    'Feature Requirements' => 'متطلبات ميزة',
    'Follow' => 'تابع',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => 'اتبع جنبا إلى جنب مع سلسلة دروس لدينا في TUTS + ونحن نبني الاجتماع خطوة مخطط بخطوة. في هذه الحلقة نتحدث عن الشركات الناشئة بشكل عام والأهداف لطلبنا .',
    'Getting Started' => 'ابدء',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'في الحلقة 2 ، ونحن خارج نطاق الميزات التي سوف نحتاج لمنتج قابل للتطبيق الحد الأدنى و مخطط قاعدة البيانات من شأنها أن تدعم ذلك.',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => 'في الحلقة 3 ، ونحن نبني كود لتمكين تلبية الأماكن، و التكامل مع HTML 5 تحديد الموقع الجغرافي ، وخرائط جوجل و جوجل الأماكن .',
    'Learn More' => 'أعرف أكثر',
    'About' => 'حول',
    'Add Current Location' => 'اضف مكان الحالي',
    'Add a Google {modelClass}' => 'إضافة جوجل {modelClass}',
    'Are you sure you want to delete this item?' => 'هل أنت متأكد أنك تريد حذف هذا البند ؟',
    'Contact' => 'اتصال',
    'Create' => 'خلق',
    'Create {modelClass}' => 'خلق {modelClass}',
    'Created At' => 'أنشئت في',
    'Created By' => 'تم إنشاؤها بواسطة',
    'Delete' => 'حذف',
    'Full Address' => 'العنوان الكامل',
    'Google Place ID' => 'جوجل مكان ID',
    'Home' => 'منزل',
    'ID' => 'الهوية',
    'Login' => 'تسجيل الدخول',
    'Logout' => 'تسجيل الخروج',
    'Meeting Type' => 'نوع الاجتماع',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => 'اجتماعات',
    'Message' => 'رسالة',
    'Name' => 'اسم',
    'Notes' => 'ملاحظات',
    'Owner ID' => 'مالك ID',
    'Place Type' => 'المكان النوع',
    'Places' => 'الأماكن',
    'Reset' => 'إعادة تعيين',
    'Search' => 'بحث',
    'Signup' => 'سجل',
    'Slug' => 'سبيكة',
    'Status' => 'وضع',
    'Update' => 'تحديث',
    'Update {modelClass}: ' => 'تحديث {modelClass} :',
    'Updated At' => 'تحديث في',
    'Vicinity' => 'جوار',
    'Website' => 'الموقع',
];