<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'A new app to make scheduling as simple as it should be.' => 'Una nueva aplicación para hacer la programación tan sencillo como debería ser .',
    'Building Places' => 'Edificios Lugares',
    'Coming Soon' => 'Próximamente',
    'Episode 1' => 'episodio 1',
    'Episode 2' => 'episodio 2',
    'Episode 3' => 'episodio 3',
    'Feature Requirements' => 'Requisitos de la característica',
    'Follow' => 'seguir',
    'Follow along with our tutorial series at Tuts+ as we build Meeting Planner step by step. In this episode we talk about startups in general and the goals for our application.' => 'Siga junto con nuestra serie de tutoriales en Tuts + A medida que construimos reuniones Planificador paso a paso. En este episodio hablamos de nuevas empresas en general y las metas para nuestra aplicación.',
    'Getting Started' => 'Empezando',
    'In Episode 2, we scope out the features that we\'ll need for a minimum viable product and the database schema that will support it.' => 'En el Episodio 2 , que alcance a cabo las funciones que vamos a necesitar para un producto viable mínimo y el esquema de base de datos que la apoyen.',
    'In Episode 3, we build code to enable meeting places, integrating with HTML 5 Geolocation, Google Maps and Google Places.' => 'En el Episodio 3 , construimos código para habilitar espacios de encuentro , integración con HTML 5 Geolocalización , Google Maps y Google Places.',
    'Learn More' => 'aprender Más',
    'About' => 'acerca de',
    'Add Current Location' => 'Agregar ubicación actual',
    'Add a Google {modelClass}' => 'Añadir un Google {modelClass}',
    'Are you sure you want to delete this item?' => '¿Estás seguro que quieres borrar este elemento?',
    'Contact' => 'contacto',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear Lugar',
    'Created At' => 'Creado El',
    'Created By' => 'Creado por',
    'Delete' => 'Eliminar',
    'Full Address' => 'Dirección completa',
    'Google Place ID' => 'Google Place ID',
    'Home' => 'casa',
    'ID' => 'ID',
    'Login' => 'Iniciar Sesión',
    'Logout' => 'Cerrar sesión',
    'Meeting Type' => 'Tipo de Reunión',
    'MeetingPlanner.io' => 'MeetingPlanner.io',
    'Meetings' => 'Encuentros',
    'Message' => 'Mensaje',
    'Name' => 'Nombre',
    'Notes' => 'Notas',
    'Owner ID' => 'Propietario ID',
    'Place Type' => 'Place Tipo',
    'Places' => 'Lugares',
    'Reset' => 'Reset',
    'Search' => 'Buscar',
    'Signup' => 'Contratar',
    'Slug' => 'Slug',
    'Status' => 'Estado',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar Lugar',
    'Updated At' => 'Actualización A',
    'Vicinity' => 'Alrededores',
    'Website' => 'Sitio Web',
];