<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Current Location' => 'Agregar ubicación actual',
    'Add a Google {modelClass}' => 'Añadir un Google {modelClass}',
    'Created By' => 'Creado por',
    'Full Address' => 'Dirección completa',
    'Google Place ID' => 'Google Place ID',
    'Name' => 'Nombre',
    'Notes' => 'Notas',
    'Place Type' => 'Place Tipo',
    'Places' => 'Lugares',
    'Slug' => 'Slug',
    'Vicinity' => 'Alrededores',
    'Website' => 'Sitio Web',
    'Are you sure you want to delete this item?' => '¿Estás seguro que quieres borrar este elemento?',
    'Create' => 'Crear',
    'Create {modelClass}' => 'Crear Lugar',
    'Created At' => 'Creado El',
    'Delete' => 'Eliminar',
    'ID' => 'ID',
    'Meeting Type' => 'Tipo de Reunión',
    'Meetings' => 'Encuentros',
    'Message' => 'Mensaje',
    'Owner ID' => 'Propietario ID',
    'Reset' => 'Reset',
    'Search' => 'Buscar',
    'Status' => 'Estado',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar Lugar',
    'Updated At' => 'Actualización A',
];
